image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet --version
      dotnet dev-certs https 
      dotnet restore
      dotnet build

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - muhammad-sammy.csharp