image: gitpod/workspace-dotnet

tasks:
  - name: Restore & Build
    init: |
      echo 'Virker ?'
      dotnet --version
      # dotnet dev-certs https 
      # dotnet restore
      # dotnet build

# vscode:
  # extensions:
    # - muhammad-sammy.csharp
